proxy_urls: 
  - name: cnproxy
    url: "http://cn-proxy.com/"
  - name: proxynova
    url: "https://www.proxynova.com/proxy-server-list/country-cn/"
proxy_domain:
  - 126.com
  - music.163.com
  - music.126.net
  - netease.com
  - akamaiedge.net

candidate_num: 20
validate_url: "http://ipservice.163.com/isFromMainland"
timeout: 10
checker_timeout: 5
check_interval: 60
# Socket params
buffer_size: 4096
delay_time: 0.001

# Proxy params
proxy_port: 9090
