proxy_urls: 
  - name: cnproxy
    url: "http://cn-proxy.com/"
  - name: proxynova
    url: "https://www.proxynova.com/proxy-server-list/country-cn/"
proxy_domain:
  - 126.com
  - music.163.com
  - music.126.net
  - netease.com
#  - akamaiedge.net

candidate_num: 20
validate_url: "http://ipservice.163.com/isFromMainland"
speedtest_url : "http://music.163.com/"
speedtest_times : 3
timeout: 5
checker_timeout: 3
check_interval: 90
# Socket params
buffer_size: 8192
delay_time: 0.01

# Proxy params
proxy_port: 9090

dns_enabled : true
dns_port : 53
upstream_dns : "8.8.8.8"