proxy_urls:
  - name: proxynova
    url: "https://www.proxynova.com/proxy-server-list/country-cn/"
  - name: cnproxy
    url: "http://cn-proxy.com/"
  - name: spysone
    url: "http://spys.one/free-proxy-list/CN/"
proxy_domain:
#  - 126.com
  - ipservice.163.com
  - music.163.com
  - ip.ws.126.net
  - m10.music.126.net

#  - music.126.net
#  - netease.com
# THIS IS FOR SOME SONG OVERSEA CDNS. IN MOST CASES YOU DON'T REALLY NEED IT
#  - e12796.f.akamaiedge.net
# If you think the speed is too slow, try adding this line. THIS WILL INCREASE THE LOAD ON HTTP PROXY SERVERS!
#   - p1.music.126.net.gccdn.net

dns_domain:
# These are the domains to be forward to this proxy, but will not go to the china proxy
#  - 126.com
#  - ipservice.163.com
  - music.163.com
  - ip.ws.126.net
  - music.httpdns.c.163.com
  - m10.music.126.net

#  - music.126.net
#  - netease.com
# THIS IS FOR SOME SONG OVERSEA CDNS. IN MOST CASES YOU DON'T REALLY NEED IT
#  - e12796.f.akamaiedge.net
#  - e12796.akamaiedge.net
## If you think the speed is too slow, try adding this line. THIS WILL INCREASE THE LOAD ON HTTP PROXY SERVERS!
#  - p1.music.126.net.gccdn.net



candidate_num: 20
validate_url: "http://ipservice.163.com/isFromMainland"

# HTTPS Related options

speedtest_url : "http://music.163.com/test"
speedtest_url_https : "https://music.163.com"

https_enabled : false

# HTTPS Related options


# Blocksites updater

enable_blocksites_updater : false
updater_url : ""

# Blocksites updater

speedtest_times : 3
timeout: 5
checker_timeout: 5
check_interval: 600
# Socket params
buffer_size: 8192
delay_time: 0.01

# Proxy params
proxy_address: "0.0.0.0"
proxy_port: 9090

dns_enabled : false
dns_port : 53

# CHANGE THE DNS IF NEEDED
upstream_dns : "8.8.8.8"

# Disable normal HTTP Proxy
# this is useful if u make a public server on the internet and avoid them to use it as a public HTTP Proxy. (Need to use with PAC or DNS)
disable_proxy : false

# Enable socks proxy
enable_socks : true
# Enable http/https proxy
enable_http : true



# Auto Generate Infos.

direct_urls :
- "*inter.iqiyi.com*"
- "*file.xiami.com*"
- "*pcvideoaliyun.titan.mgtv.com*"
- "*vhotlx.video.qq.com*"
- "*newflv.sohu.ccgslb.net*"