proxy_url: "http://cn-proxy.com"
proxy_domain:
  - 126.com
  - music.163.com
  - music.126.net
  - netease.com

candidate_num: 20
validate_url: "http://cdn.bootcss.com/angular.js/2.0.0-beta.17/angular2-all.umd.js"
timeout: 10
check_interval: 600
# Socket params
buffer_size: 4096
delay_time: 0.001

# Proxy params
proxy_port: 9090
# proxy_ip: "127.0.0.1" ## This field overrides the get_ip feature.
